CREATE DATABASE IF NOT EXISTS proy_libreria;

USE proy_libreria;

CREATE TABLE libros (
    idLibro INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(50) NULL DEFAULT NULL,
    autor VARCHAR(50) NULL DEFAULT NULL,
    anioPublicacion SMALLINT(4) NULL DEFAULT NULL,
    cantidadDisponible SMALLINT(6) NULL DEFAULT NULL,
    PRIMARY KEY (idLibro)
) ENGINE=InnoDB;

CREATE TABLE usuarios (
    ID INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    Usuario VARCHAR(30) NULL DEFAULT 'Usuario',
    Contrasena VARCHAR(64) NOT NULL DEFAULT '0',
    PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=35;


